# Generated by Django 3.0 on 2019-12-11 23:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='Usuario',
            field=models.OneToOneField(null=True, on_delete=django.utils.timezone.now, to='landing.Usuario'),
        ),
    ]
