# Generated by Django 3.0 on 2019-12-11 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_aluno_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='Usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Usuario'),
        ),
    ]
